version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongodb-db-network

volumes:
  mongodb-data:
    driver: local

networks:
  mongodb-db-network:
    driver: bridge
