version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-db-network

volumes:
  redis-data:
    driver: local

networks:
  redis-db-network:
    driver: bridge
